debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.fastcampus.projectboard: debug
    org.springframework.web.servlet: debug
    #org.hibernate.type.descriptor.sql.BasicBinder: trace  # Hibernate 5.x
    org.hibernate.orm.jdbc.bind: TRACE # Hibernate 6.x
#    org.springframework.boot.autoconfigure.data.rest: TRACE
#    org.springframework.data: DEBUG
#    org.springframework.data.rest: TRACE
#    org.springframework.data.rest.webmvc: TRACE
#    org.springframework.data.rest.core: TRACE

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
#    url: jdbc:mysql://192.168.0.66:3307/board
#    username: jino
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always

  data:
    rest:
      basePath: /api
      detection-strategy: annotated
